# Test FreeBSD in a full VM on cirrus-ci.com.  Test the i686 target too, in the
# same VM.  The binary will be built in 32-bit mode, but will execute on a
# 64-bit kernel and in a 64-bit environment.  Our tests don't execute any of
# the system's binaries, so the environment shouldn't matter.
task:
  name: FreeBSD 11.4
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  freebsd_instance:
    image: freebsd-11-4-release-amd64
  # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain 1.36.0
    - $HOME/.cargo/bin/rustup target add i686-unknown-freebsd
  amd64_test_script:
    - . $HOME/.cargo/env
    - cargo test
  i386_test_script:
    - . $HOME/.cargo/env
    - cargo test --target i686-unknown-freebsd
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: Linux
  container:
    image: rust:1.24.1
  env:
    matrix:
      - TARGET: x86_64-unknown-linux-gnu
      - TARGET: i686-unknown-linux-gnu
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - uname -a
    - cat /etc/debian_version
    - cat /proc/cpuinfo
    - cat /proc/crypto
  test_script:
    - sh ci/script.sh

task:
  name: Linux/GNU x86_64 stable
  container:
    image: rust:latest
  env:
    TARGET: x86_64-unknown-linux-gnu
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - uname -a
    - cat /etc/debian_version
    - cat /proc/cpuinfo
    - cat /proc/crypto
  test_script:
    - sh ci/script.sh
