[package]

name        = "nix"
description = "Rust friendly bindings to Posix APIs"
version     = "0.1.1"
authors     = ["Carl Lerche <me@carllerche.com>"]
homepage    = "https://github.com/carllerche/nix-rust"
license     = "MIT"
