[package]

name        = "nix"
description = "Rust friendly bindings to Posix APIs"
version     = "0.2.0"
authors     = ["Carl Lerche <me@carllerche.com>"]
homepage    = "https://github.com/carllerche/nix-rust"
license     = "MIT"
exclude     = [".gitignore", ".travis.yml", "tests/**/*"]

[dependencies]
bitflags = "0.1"

[dev-dependencies]
rand = "0.1.2"
